version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Strong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P Strong!Passw0rd -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
    #command: >
      #bash -c " /opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Strong!Passw0rd -Q 'CREATE DATABASE Medilabo' && wait"

  medilabo.api:
    build:
      context: ./MediLabo
      dockerfile: Dockerfile
    container_name: medilabo.api
    ports:
      - "5001:8080"
      - "5002:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Medilabo;User Id=sa;Password=Strong!Passw0rd;TrustServerCertificate=True
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - backend

  gateway.ocelot:
    build:
      context: ./Gateway.Ocelot
      dockerfile: Dockerfile
    container_name: gateway.ocelot
    ports:
      - "6000:8080"
      - "6001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - medilabo.api
    networks:
      - backend

networks:
  backend: