version: '3.8'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Strong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Strong!Passw0rd", "-Q", "SELECT 1"]
      # test: ["CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Strong!Passw0rd"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo_data:/data/db

  medilabo.api:
    build:
      context: ./MediLabo
      dockerfile: Dockerfile
    container_name: medilabo.api
    ports:
      - "5001:8080"
      - "5002:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Medilabo;User Id=sa;Password=Strong!Passw0rd;TrustServerCertificate=True
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - backend

  gateway.ocelot:
    build:
      context: ./Gateway.Ocelot
      dockerfile: Dockerfile
    container_name: gateway.ocelot
    ports:
      - "6000:8080"
      - "6001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - medilabo.api
    networks:
      - backend
      
volumes:
  mongo_data:

networks:
  backend: